# Generated by Django 3.1.6 on 2021-03-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210302_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('Мужчина', 'Man'), ('Женщина', 'Woman')], default='Мужчина', max_length=7),
        ),
    ]
