# Generated by Django 3.1.6 on 2021-02-15 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Waiting', max_length=8)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('location', models.CharField(max_length=120)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('increment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('prize_fund', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Current', 'current'), ('Forthcoming', 'forthcoming'), ('Completed', 'completed')], default='Forthcoming', max_length=11)),
                ('mode', models.CharField(choices=[('FIDE', 'FIDE'), ('ФШР', 'ФШР'), ('Без обсчёта', 'Без обсчёта')], default='Без обсчёта', max_length=11)),
                ('rating_type', models.CharField(choices=[('Классика', 'Классика'), ('Рапид', 'Рапид'), ('Блиц', 'Блиц'), ('Пуля', 'Пуля'), ('Классика FIDE', 'Классика FIDE'), ('Шахматы 960', 'Шахматы 960')], default='Классика', max_length=13)),
                ('organizer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='tournaments', through='tournaments.Participation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('player', 'tournament')},
        ),
    ]
