# Generated by Django 3.1.6 on 2021-02-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='waiting', max_length=8),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('Классика', 'Классика'), ('Рапид', 'Рапид'), ('Блиц', 'Блиц'), ('Пуля', 'Пуля'), ('Классика FIDE', 'Классика FIDE'), ('Шахматы 960', 'Шахматы 960')], default='Классика', max_length=13),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rating_type',
            field=models.CharField(choices=[('FIDE', 'FIDE'), ('ФШР', 'ФШР'), ('Без обсчёта', 'Без обсчёта')], default='Без обсчёта', max_length=11),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('current', 'current'), ('forthcoming', 'forthcoming'), ('completed', 'completed')], default='forthcoming', max_length=11),
        ),
        migrations.CreateModel(
            name='AnonymousParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='waiting', max_length=8)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_participants', to='tournaments.tournament')),
            ],
        ),
    ]
